let monsters = [
{
      name: "Ochre Jelly",
      envirement: new Set(['hill']),
      challenge_rating:"2",
      alignment:  "unaligned",
      size: "large",
      type: "ooze",
      page: "243",
      xp: 450,
      armorClass: 8 ,
      hitPoints: 45,
      Speed: 10 ,
      STR: 15,
      STR_mod: (+2),
      DEX: 6,
      DEX_mod: (-2),
      CON: 14,
      CON_mod: (+2),
      INT: 2,
      INT_mod: (-4),
      WIS: 6,
      WIS_mod: (-2),
      CHA: 1,
      CHA_mod: (-5),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/279/1000/1000/636252770058723674.jpeg"
    },
    {
      name: "Octopus",
      envirement: new Set(['aquatic']),
      challenge_rating:"0",
      size: "small",
      type: "beast",
      page: "333",
      xp: 10,
      alignment: "unaligned",
      armorClass: 12 ,
      hitPoints: 3, 
      Speed: 5,
      STR: 4,
      STR_mod: (-3),
      DEX: 15,
      DEX_mod: (+2),
      CON: 11,
      CON_mod: (+0),
      INT: 3,
      INT_mod: (-4),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 4,
      CHA_mod: (-3),
      Challenge: 10,
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/9/921/315/315/636334602449110996.jpeg"
    },
    {
      name: "Ogre",
      envirement: new Set(['hill', 'arctic', 'coastal', 'desert', 'forest', 'grass land', 'mountain', 'swamp', 'underground']),
      challenge_rating:"2",
      size: "large",
      type: "giant",
      page: "237",
      xp: 450,
      alignment: "chaotic evil",
      armorClass: 11,
      hitPoints: 59,
      Speed: 40,
      STR: 19,
      STR_mod: (+4),
      DEX: 8,
      DEX_mod: (-1),
      CON: 16,
      CON_mod: (+3),
      INT: 5,
      INT_mod: (-3),
      WIS: 7,
      WIS_mod: (-2),
      CHA: 7,
      CHA_mod: (-2),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/285/315/315/636252770535203221.jpeg"
    },
    {
      name: "Ogre Zombie",
      envirement: new Set(['hill', 'arctic', 'coastal', 'desert', 'forest', 'grass land', 'mountain', 'swamp', 'underground']),
      challenge_rating:"2",
      size: "large",
      type: "undead",
      page: "316",
      xp: 450,
      alignment: " neutral evil",
      armorClass: 8 ,
      hitPoints: 85,
      Speed: 30,
      STR: 19,
      STR_mod: (+4),
      DEX: 6,
      DEX_mod: (-2),
      CON: 18,
      CON_mod: (+4),
      INT: 3,
      INT_mod: (-4),
      WIS: 6,
      WIS_mod: (-2),
      CHA: 5,
      CHA_mod: (-3),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/287/315/315/636252770700032248.jpeg"
    },
    {
      name: "Oni",
      envirement: new Set(['urban', 'forest']),
      challenge_rating:"7",
      size: "large",
      xp: 2900,
      type: "giant",
      page: "239",
      alignment:  "lawful evil",
      armorClass: 16 ,
      hitPoints: 110,
      Speed: 30,
      STR: 19,
      STR_mod: (+4),
      DEX: 11,
      DEX_mod: (+0),
      CON: 16,
      CON_mod: (+3),
      INT: 14,
      INT_mod: (+2),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 15,
      CHA_mod: (+2), 
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/297/1000/1000/636252771507213738.jpeg"
    },
    {
      name: "Orc",
      envirement: new Set(['hill', 'arctic', 'forest', 'grass land', 'mountain', 'swamp', 'underground']),
      challenge_rating:"1/2",
      xp: 100,
      alignment:  "chaotic evil",
      size: "medium",
      type: "humanoid",
      page: "246",
      armorClass: 13,
      hitPoints: 15 ,
      Speed: 30,
      STR: 16,
      STR_mod: (+3),
      DEX: 12,
      DEX_mod: (+1),
      CON: 16,
      CON_mod: (+3),
      INT: 7,
      INT_mod: (-2),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 10,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/301/1000/1000/636252771691385727.jpeg"
    },
    {
      name: "Otyugh",
      envirement: new Set(['underground']),
      challenge_rating:"5",
      xp: 1800,
      size: "large",
      type: "abberation",
      page: "248",
      alignment: "nuetral",
      armorClass: 14,
      hitPoints: 114 ,
      Speed: 30,
      STR: 16,
      STR_mod: (+3),
      DEX: 11,
      DEX_mod: (+0),
      CON: 19,
      CON_mod: (+4),
      INT: 6,
      INT_mod: (-2),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 6,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/305/315/315/636252771931366466.jpeg"
    },
    {
      name: "Owl",
      envirement: new Set(['arctic', 'forest',]),
      challenge_rating:"0",
      size: "tiny",
      type: "beast",
      page: "333",
      xp: 10,
      alignment:  "unaligned",
      armorClass: 11 ,
      hitPoints: 1 ,
      Speed: 5,
      STR: 3,
      STR_mod: (-4),
      DEX: 13,
      DEX_mod: (+1),
      CON: 8,
      CON_mod: (-1),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 7,
      CHA_mod: (-2),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/533/1000/1000/636376331660233857.jpeg"
    },
    {
      name: "Owlbear",
      envirement: new Set(['forest']),
      challenge_rating:"3",
      size: "large",
      type: "monstrosity",
      page: "249",
      xp: 700,
      alignment:  "unaligned",
      armorClass: 13,
      hitPoints: 59 ,
      Speed: 40,
      STR: 20,
      STR_mod: (+5),
      DEX: 12,
      DEX_mod: (+1),
      CON: 17,
      CON_mod: (+3),
      INT: 3,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 7,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/315/315/315/636252772225295187.jpeg"
    },
    {
      name: "Panther",
      envirement: new Set(['hill', 'forest', 'grass land']),
      challenge_rating:"1/4",
      size: "medium",
      type: "beast",
      page: "333",
      xp: 50,
      alignment: "unaligned",
      armorClass: 12 ,
      hitPoints: 13 ,
      Speed: 50 ,
      STR: 14,
      STR_mod: (+2),
      DEX: 15,
      DEX_mod: (+2),
      CON: 10,
      CON_mod: (+0),
      INT: 3,
      INT_mod: (-4),
      WIS: 14,
      WIS_mod: (+2),
      CHA: 7,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Pegasus",
      envirement: new Set(['hill', 'forest', 'grass land']),
      challenge_rating:"2",
      size: "large",
      type: "celestial",
      page: "250",
      xp: 450,
      alignment:" chaotic good",
      armorClass: 12 ,
      hitPoints: 59 ,
      Speed: 60 ,
      STR: 18,
      STR_mod: (+4),
      DEX: 15,
      DEX_mod: (+2),
      CON: 16,
      CON_mod: (+3),
      INT: 10,
      INT_mod: (+0),
      WIS: 15,
      WIS_mod: (+2),
      CHA: 13,
      CHA_mod: (+1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/18/303/1000/1000/636379808797059368.png"
    },
    {
      name: "Phase Spider",
      envirement: new Set(['hill', 'desert', 'forest', 'grass land', 'urban', 'underground']),
      challenge_rating:"3",
      size: "large",
      type: "monstrosity",
      page: "334",
      xp: 700,
      alignment: "unaligned",
      armorClass: 13,
      hitPoints: 32 ,
      Speed: 30,
      STR: 15,
      STR_mod: (+2),
      DEX: 15,
      DEX_mod: (+2),
      CON: 12,
      CON_mod: (+1),
      INT: 6,
      INT_mod: (-2),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 6,
      CHA_mod: (-2),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/319/315/315/636252772538300448.jpeg"
    },
    {
      name: "Pit Fiend",
      envirement: new Set(['any']),
      challenge_rating:"20",
      size: "large",
      type: "fiend",
      page: "77",
      xp: 25000,
      alignment: "lawful evil",
      armorClass: 19,
      hitPoints: 300 ,
      Speed: 30 ,
      STR: 26,
      STR_mod: (+8),
      DEX: 14,
      DEX_mod: (+2),
      CON: 24,
      CON_mod: (+7),
      INT: 22,
      INT_mod: (+6),
      WIS: 18,
      WIS_mod: (+4),
      CHA: 24,
      CHA_mod: (+7),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/311/315/315/636252772132434763.jpeg"
    },
    {
      name: "Planetar",
      envirement: new Set(['any']),
      challenge_rating:"16",
      size: "large",
      type: "celestial",
      page: "17",
      xp: 15000,
      alignment:  "lawful good",
      armorClass: 19,
      hitPoints: 200,
      Speed: 40,
      STR: 24,
      STR_mod: (+7),
      DEX: 20,
      DEX_mod: (+5),
      CON: 24,
      CON_mod: (+7),
      INT: 19,
      INT_mod: (+4),
      WIS: 22,
      WIS_mod: (+6),
      CHA: 25,
      CHA_mod: (+7),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/303/315/315/636252771762002496.jpeg"
    },
    {
      name: "Plesiosaurus",
      envirement: new Set(['coastal', 'aquatic']),
      challenge_rating:"2",
      size: "large",
      type: "beast",
      page: "80",
      xp: 450,
      alignment:  "unaligned",
      armorClass: 13,
      hitPoints: 68 ,
      Speed: 20,
      STR: 18,
      STR_mod: (+4),
      DEX: 15,
      DEX_mod: (+2),
      CON: 16,
      CON_mod: (+3),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 5,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/488/315/315/636376304583147024.jpeg"
    },
    {
      name: "Poisonous Snake",
      envirement: new Set(['coastal', 'desert', 'forrest', 'grass land', 'hill', 'swamp']),
      challenge_rating:"1/8",
      size: "tiny",
      type: "beast",
      page: "334",
      xp: 25,
      alignment:  "unaligned",
      armorClass: 13 ,
      hitPoints: 2 ,
      Speed: 30 ,
      STR: 2,
      STR_mod: (-4),
      DEX: 16,
      DEX_mod: (+3),
      CON: 11,
      CON_mod: (+0),
      INT: 1,
      INT_mod: (-5),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 3,
      CHA_mod: (-4),
      img_url:" https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name:" Polar Bear",
      envirement: new Set(['arctic', 'underground']),
      challenge_rating:"2",
      size: "large",
      type: "beast",
      page: "334",
      xp: 450,
      alignment:  "unaligned",
      armorClass: 12,
      hitPoints: 42,
      Speed: 40,
      STR: 20,
      STR_mod: (+5),
      DEX: 10,
      DEX_mod: (+0),
      CON: 16,
      CON_mod: (+3),
      INT: 2,
      INT_mod: (-4),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 7,
      CHA_mod: (-2),
      img_url:" https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Pony",
      envirement: new Set(['urban']),
      challenge_rating:"1/8",
      size: "medium",
      type: "beast",
      page: "335",
      xp: 25,
      alignment: "unaligned",
      armorClass: 10 ,
      hitPoints: 11 ,
      Speed: 40,
      STR: 15,
      STR_mod: (+2),
      DEX: 10,
      DEX_mod: (+0),
      CON: 13,
      CON_mod: (+1),
      INT: 2,
      INT_mod: (-4),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 7,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Priest",
      envirement: new Set(['any']),
      challenge_rating:"2",
      size: "medium",
      type: "humanoid",
      page: "348",
      xp: 450,
      alignment: "any",
      armorClass: 13,
      hitPoints: 27 ,
      Speed: 25,
      STR: 10,
      STR_mod: (+0),
      DEX: 10,
      DEX_mod: (+0),
      CON: 12,
      CON_mod: (+1),
      INT: 13,
      INT_mod: (+1),
      WIS: 16,
      WIS_mod: (+3),
      CHA: 13,
      CHA_mod: (+1),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/656/humanoid.jpg"
    },
    {
      name: "Pseudodragon",
      envirement: new Set(['coastal', 'desert', 'forrest', 'mountain', 'hill', 'urban']),
      challenge_rating:"1/4",
      size: "tiny",
      type: "dragon",
      page: "254",
      xp: 50,
      alignment:"neutral good",
      armorClass: 13,
      hitPoints: 7 ,
      Speed: 15,
      STR: 6,
      STR_mod: (-2),
      DEX: 15,
      DEX_mod: (+2),
      CON: 13,
      CON_mod: (+1),
      INT: 10,
      INT_mod: (+0),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 10,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/283/1000/1000/636252770521719244.jpeg"
    },
    {
      name: "Pteranodon",
      envirement: new Set(['coastal', 'grass land', 'mountain']),
      challenge_rating:"1/4",
      size: "medium",
      type: "beast",
      page: "80",
      xp: 50,
      alignment: "unaligned",
      armorClass: 13,
      hitPoints: 13 ,
      Speed: 10,
      STR: 12,
      STR_mod: (+1),
      DEX: 15,
      DEX_mod: (+2),
      CON: 10,
      CON_mod: (+0),
      INT: 2,
      INT_mod: (-4),
      WIS: 9,
      WIS_mod: (-1),
      CHA: 5,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name:"Purple Worm",
      envirement: new Set(['desert', 'underground']),
      challenge_rating:"15",
      size: "gargantuan",
      type: "monstrosity",
      page: "225",
      xp: 13000,
      alignment: "unaligned",
      armorClass: 18,
      hitPoints: 247, 
      Speed: 50,
      STR: 28,
      STR_mod: (+9),
      DEX: 7,
      DEX_mod: (-2),
      CON: 22,
      CON_mod: (+6),
      INT: 1,
      INT_mod: (-5),
      WIS: 8,
      WIS_mod: (-1),
      CHA: 4,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/275/315/315/636252769846436684.jpeg"
    },
    {
      name: "Quasit",
      envirement: new Set(['any']),
      challenge_rating:"1",
      size: "tiny",
      type: "fiend",
      page: "63",
      xp: 200,
      alignment: "chaotic evil",
      armorClass: 13 ,
      hitPoints: 7,
      Speed: 40,
      STR: 5,
      STR_mod: (-3),
      DEX: 17,
      DEX_mod: (+3),
      CON: 10,
      CON_mod: (+0),
      INT: 7,
      INT_mod: (-2),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 10,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/271/315/315/636252769318699115.jpeg"
    },
    {
      name: "Quipper",
      envirement: new Set(['aquatic']),
      challenge_rating:"0",
      size: "tiny",
      type: "beast",
      page: "335",
      xp: 10,
      alignment:  "unaligned",
      armorClass: 13 ,
      hitPoints: 1 ,
      Speed: 0,
      STR: 2,
      STR_mod: (-4),
      DEX: 16,
      DEX_mod: (+3),
      CON: 9,
      CON_mod: (-1),
      INT: 1,
      INT_mod: (-5),
      WIS: 7,
      WIS_mod: (-2),
      CHA: 2,
      CHA_mod: (-4),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/253/1000/1000/636252767919065233.jpeg"
    },
    {
      name: "Rakshasa",
      envirement: new Set(['urban']),
      challenge_rating:"13",
      size: "medium",
      type: "fiend",
      page: "257",
      xp: 10000,
      alignment:  "lawful evil",
      armorClass: 16,
      hitPoints: 110,
      Speed: 40,
      STR: 14,
      STR_mod: (+2),
      DEX: 17,
      DEX_mod: (+3),
      CON: 18,
      CON_mod: (+4),
      INT: 13,
      INT_mod: (+1),
      WIS: 16,
      WIS_mod: (+3),
      CHA: 20,
      CHA_mod: (+5),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/247/315/315/636252767480157951.jpeg"
    },
    {
      name: "Rat",
      envirement: new Set(['urban', 'swamp']),
      challenge_rating:"0",
      size: "tiny",
      type: "beast",
      page: "335",
      xp: 10,
      alignment:  "unaligned",
      armorClass: 10 ,
      hitPoints: 1 ,
      Speed: 20,
      STR: 2,
      STR_mod: (-4),
      DEX: 11,
      DEX_mod: (+0),
      CON: 9,
      CON_mod: (-1),
      INT: 2,
      INT_mod: (-4),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 4,
      CHA_mod: (-3),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/541/315/315/636376335435407571.jpeg"
    },
    {
      name: "Raven",
      envirement: new Set(['urban', 'hill', 'swamp']),
      challenge_rating:"0",
      size: "tiny",
      type: "beast",
      page: "335",
      xp: 10,
      alignment: "unaligned",
      armorClass: 12 ,
      hitPoints: 1,
      Speed: 10 ,
      STR: 2,
      STR_mod: (-4),
      DEX: 14,
      DEX_mod: (+2),
      CON: 8,
      CON_mod: (-1),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 6,
      CHA_mod: (-2),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/553/1000/1000/636376341568391037.jpeg"
    },
    {
      name: "Red Dragon Wyrmling",
      envirement: new Set(['any']),
      challenge_rating:"4",
      size: "medium",
      type: "dragon",
      page: "98",
      xp: 1100,
      alignment:  "chaotic evil",
      armorClass: 17,
      hitPoints: 75 ,
      Speed: 30,
      STR: 19,
      STR_mod: (+4),
      DEX: 10,
      DEX_mod: (+0),
      CON: 17,
      CON_mod: (+3),
      INT: 12,
      INT_mod: (+1),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 15,
      CHA_mod: (+2),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/239/315/315/636252766855622680.jpeg"
    },
    {
      name: "Reef Shark",
      envirement: new Set(['aquatic']),
      challenge_rating:"1/2",
      size: "medium",
      type: "beast",
      page: "336",
      xp: 100,
      alignment: "unaligned",
      armorClass: 12,
      hitPoints: 22 ,
      Speed: 0 ,
      STR: 14,
      STR_mod: (+2),
      DEX: 13,
      DEX_mod: (+1),
      CON: 13,
      CON_mod: (+1),
      INT: 1,
      INT_mod: (-5),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 4,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Remorhaz",
      envirement: new Set(['arctic']),
      challenge_rating:"11",
      size: "huge",
      type: "monstrosity",
      page: "258",
      xp: 7200,
      alignment:  "unaligned",
      armorClass: 17,
      hitPoints: 195,
      Speed: 30 ,
      STR: 24,
      STR_mod: (+7),
      DEX: 13,
      DEX_mod: (+1),
      CON: 21,
      CON_mod: (+5),
      INT: 4,
      INT_mod: (-3),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 5,
      CHA_mod: (-3),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/231/315/315/636252766143328421.jpeg"
    },
    {
      name: "Rhinoceros",
      envirement: new Set(['grass land']),
      challenge_rating:"2",
      size: "large",
      type: "beast",
      page: "336",
      xp: 450,
      alignment: "unaligned",
      armorClass: 11,
      hitPoints: 45,
      Speed: 40,
      STR: 21,
      STR_mod: (+5),
      DEX: 8,
      DEX_mod: (-1),
      CON: 15,
      CON_mod: (+2),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 6,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name:" Riding Horse",
      envirement: new Set(['grass land' ,'urban']),
      challenge_rating:"1/4",
      size: "large",
      type: "beast",
      page: "336",
      xp: 50,
      alignment:  "unaligned",
      armorClass: 10 ,
      hitPoints: 13 ,
      Speed: 60,
      STR: 16,
      STR_mod: (+3),
      DEX: 10,
      DEX_mod: (+0),
      CON: 12,
      CON_mod: (+1),
      INT: 2,
      INT_mod: (-4),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 7,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/9/904/315/315/636334288913250513.jpeg"
    },
    {
      name: "Roc",
      envirement: new Set(['coastal', 'desert', 'hill', 'mountain', 'arctic']),
      challenge_rating:"11",
      size: "gargantuan",
      type: "monstrosity",
      page: "260",
      xp: 7200,
      alignment: "unaligned",
      armorClass: 15,
      hitPoints: 248 ,
      Speed: 20,
      STR: 28,
      STR_mod: (+9),
      DEX: 10,
      DEX_mod: (+0),
      CON: 20,
      CON_mod: (+5),
      INT: 3,
      INT_mod: (-4),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 9,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/229/315/315/636252765590929622.jpeg"
    },
    {
      name: "Roper",
      envirement: new Set(['underground']),
      challenge_rating:"5",
      size: "large",
      type: "monstrosity",
      page: "261",
      xp: 1800,
      alignment: " neutral evil",
      armorClass: 20,
      hitPoints: 93,
      Speed: 10,
      STR: 18,
      STR_mod: (+4),
      DEX: 8,
      DEX_mod: (-1),
      CON: 17,
      CON_mod: (+3),
      INT: 7,
      INT_mod: (-2),
      WIS: 16,
      WIS_mod: (+3),
      CHA: 6,
      CHA_mod: (-2),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/560/1000/1000/636376344528091115.jpeg"
    },
    {
      name: "Rug of Smothering",
      envirement: new Set(['any']),
      challenge_rating:"2",
      size: "large",
      type: "construct",
      page: "20",
      xp: 450,
      alignment: "unaligned",
      armorClass: 12 ,
      hitPoints: 33 ,
      Speed: 10,
      STR: 17,
      STR_mod: (+3),
      DEX: 14,
      DEX_mod: (+2),
      CON: 10,
      CON_mod: (+0),
      INT: 1,
      INT_mod: (-5),
      WIS: 3,
      WIS_mod: (-4),
      CHA: 1,
      CHA_mod: (-5),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/213/1000/1000/636252764761726261.jpeg"
    },
    {
      name: "Rust Monster",
      envirement: new Set(['underground']),
      challenge_rating:"1/2",
      size: "medium",
      type: "monstrosity",
      page: "262",
      xp: 100,
      alignment: "unaligned",
      armorClass: 14,
      hitPoints: 27,
      Speed: 40,
      STR: 13,
      STR_mod: (+1),
      DEX: 12,
      DEX_mod: (+1),
      CON: 13,
      CON_mod: (+1),
      INT: 2,
      INT_mod: (-4),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 6,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/207/1000/1000/636252764265020108.jpeg"
    },
    {
      name: "Saber-Toothed Tiger",
      envirement: new Set(['arctic', 'mountain']),
      challenge_rating:"2",
      size: "large",
      type: "beast",
      page: "336",
      xp: 450,
      alignment:  "unaligned",
      armorClass: 12 ,
      hitPoints: 52 ,
      Speed: 40,
      STR: 18,
      STR_mod: (+4),
      DEX: 14,
      DEX_mod: (+2),
      CON: 15,
      CON_mod: (+2),
      INT: 3,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Sahuagin",
      envirement: new Set(['aquatic', 'coastal']),
      challenge_rating:"1/2",
      size: "medium",
      type: "humanoid",
      page: "263",
      xp: 100,
      alignment: " lawful evil",
      armorClass: 12,
      hitPoints: 22,
      Speed: 30,
      STR: 13,
      STR_mod: (+1),
      DEX: 11,
      DEX_mod: (+0),
      CON: 12,
      CON_mod: (+1),
      INT: 12,
      INT_mod: (+1),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 9,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/177/1000/1000/636252761683746719.jpeg"
    },
    {
      name: "Salamander",
      envirement: new Set(['underground']),
      challenge_rating:"5",
      size: "large",
      type: "elemental",
      page: "266",
      xp: 1800,
      alignment:  "neutral evil",
      armorClass: 15,
      hitPoints: 90 ,
      Speed: 30,
      STR: 18,
      STR_mod: (+4),
      DEX: 14,
      DEX_mod: (+2),
      CON: 15,
      CON_mod: (+2),
      INT: 11,
      INT_mod: (+0),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 12,
      CHA_mod: (+1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/173/1000/1000/636252761197608364.jpeg"
    },
    {
      name: "Satyr",
      envirement: new Set(['forrest']),
      challenge_rating:"1/2",
      size: "medium",
      type: "fey",
      page: "267",
      xp: 100,
      alignment: "chaotic neutral",
      armorClass: 14,
      hitPoints: 31,
      Speed: 40,
      STR: 12,
      STR_mod: (+1),
      DEX: 16,
      DEX_mod: (+3),
      CON: 11,
      CON_mod: (+0),
      INT: 12,
      INT_mod: (+1),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 14,
      CHA_mod: (+2),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/169/1000/1000/636252760706340605.jpeg"
    },
    {
      name: "Scorpion",
      envirement: new Set(['desert']),
      challenge_rating:"0",
      size: "tiny",
      type: "beast",
      page: "337",
      xp: 10,
      alignment:  "unaligned",
      armorClass: 11,
      hitPoints: 1,
      Speed: 10,
      STR: 2,
      STR_mod: (-4),
      DEX: 11,
      DEX_mod: (+0),
      CON: 8,
      CON_mod: (-1),
      INT: 1,
      INT_mod: (-5),
      WIS: 8,
      WIS_mod: (-1),
      CHA: 2,
      CHA_mod: (-4),
      img_url:" https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Scout",
      envirement: new Set(['any']),
      challenge_rating:"1/2",
      size: "medium",
      type: "humanoid",
      page: "349",
      xp: 100,
      alignment:  "any",
      armorClass: 13,
      hitPoints: 16 ,
      Speed: 30,
      STR: 11,
      STR_mod: (+0),
      DEX: 14,
      DEX_mod: (+2),
      CON: 12,
      CON_mod: (+1),
      INT: 11,
      INT_mod: (+0),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 11,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/163/1000/1000/636252759915100020.jpeg"
    },
    {
      name: "Sea Hag",
      envirement: new Set(['coastal', 'aquatic']),
      challenge_rating:"2",
      size: "medium",
      type: "fey",
      page: "179",
      xp: 450,
      alignment: " chaotic evil",
      armorClass: 14,
      hitPoints: 52,
      Speed: 30,
      STR: 16,
      STR_mod: (+3),
      DEX: 13,
      DEX_mod: (+1),
      CON: 16,
      CON_mod: (+3),
      INT: 12,
      INT_mod: (+1),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 13,
      CHA_mod: (+1),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/159/1000/1000/636252759356069260.jpeg"
    },
    {
      name: "Sea Horse",
      envirement: new Set(['aquatic']),
      challenge_rating:"0",
      size: "tiny",
      type: "beast",
      page: "337",
      xp: 10,
      alignment: "unaligned",
      armorClass: 11 ,
      hitPoints: 1 ,
      Speed: 0 ,
      STR: 1,
      STR_mod: (-5),
      DEX: 12,
      DEX_mod: (+1),
      CON: 8,
      CON_mod: (-1),
      INT: 1,
      INT_mod: (-5),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 2,
      CHA_mod: (-4),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Shadow",
      envirement: new Set(['urban', 'underground']),
      challenge_rating:"1/2",
      size: "medium",
      type: "undead",
      page: "269",
      xp: 100,
      alignment:  "chaotic evil",
      armorClass: 12 ,
      hitPoints: 16,
      Speed: 40,
      STR: 6,
      STR_mod: (-2),
      DEX: 14,
      DEX_mod: (+2),
      CON: 13,
      CON_mod: (+1),
      INT: 6,
      INT_mod: (-2),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 8,
      CHA_mod: (-1),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/155/315/315/636252758977032019.jpeg"
    },
    {
      name: "Shambling Mound",
      envirement: new Set(['forrest', 'swamp']),
      challenge_rating:"5",
      size: "large",
      type: "plant",
      page: "270",
      xp: 1800,
      alignment:  "unaligned",
      armorClass: 15,
      hitPoints: 136 ,
      Speed: 20,
      STR: 18,
      STR_mod: (+4),
      DEX: 8,
      DEX_mod: (-1),
      CON: 16,
      CON_mod: (+3),
      INT: 5,
      INT_mod: (-3),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 5,
      CHA_mod: (-3),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/563/315/315/636376346968079714.jpeg"
    },
    {
      name: "Shield Guardian",
      envirement: new Set(['urban']),
      challenge_rating:"7",
      size: "large",
      type: "construct",
      page: "271",
      xp: 2900,
      alignment:  "unaligned",
      armorClass: 17,
      hitPoints: 142 ,
      Speed: 30,
      STR: 18,
      STR_mod: (+4),
      DEX: 8,
      DEX_mod: (-1),
      CON: 18,
      CON_mod: (+4),
      INT: 7,
      INT_mod: (-2),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 3,
      CHA_mod: (-4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/145/315/315/636252758362792494.jpeg"
    },
    {
      name: "Shrieker",
      envirement: new Set(['underground']),
      challenge_rating:"0",
      size: "medium",
      type: "plant",
      page: "138",
      xp: 10,
      alignment:"unaligned",
      armorClass: 5 ,
      hitPoints: 13 ,
      Speed: 0,
      STR: 1,
      STR_mod: (-5),
      DEX: 1,
      DEX_mod: (-5),
      CON: 10,
      CON_mod: (+0),
      INT: 1,
      INT_mod: (-5),
      WIS: 3,
      WIS_mod: (-4),
      CHA: 1,
      CHA_mod: (-5),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/571/1000/1000/636376357634308010.jpeg"
    },
    {
      name: "Silver Dragon Wyrmling",
      envirement: new Set(['any']),
      challenge_rating:"2",
      size: "medium",
      type: "dragon",
      page: "118",
      xp: 450,
      alignment: "lawful good",
      armorClass: 17,
      hitPoints: 45,
      Speed: 30,
      STR: 19,
      STR_mod: (+4),
      DEX: 10,
      DEX_mod: (+0),
      CON: 17,
      CON_mod: (+3),
      INT: 12,
      INT_mod: (+1),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 15,
      CHA_mod: (+2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/143/315/315/636252757538355953.jpeg"
    },
    {
      name: "Skeleton",
      envirement: new Set(['urban']),
      challenge_rating:"1/4",
      size: "medium",
      type: "undead",
      page: "272",
      xp: 50,
      alignment: "lawful evil",
      armorClass: 13,
      hitPoints: 13,
      Speed: 30,
      STR: 10,
      STR_mod: (+0),
      DEX: 14,
      DEX_mod: (+2),
      CON: 15,
      CON_mod: (+2),
      INT: 6,
      INT_mod: (-2),
      WIS: 8,
      WIS_mod: (-1),
      CHA: 5,
      CHA_mod: (-3),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/472/315/315/636376294573239565.jpeg"
    },
    {
      name: "Solar",
      envirement: new Set(['any']),
      challenge_rating:"18",
      size: "large",
      type: "celestial",
      page: "18",
      xp: 33000,
      alignment:  "lawful good",
      armorClass: 21,
      hitPoints: 243,
      Speed: 50,
      STR: 26,
      STR_mod: (+8),
      DEX: 22,
      DEX_mod: (+6),
      CON: 26,
      CON_mod: (+8),
      INT: 25,
      INT_mod: (+7),
      WIS: 25,
      WIS_mod: (+7),
      CHA: 30,
      CHA_mod: (+10),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/121/315/315/636252748079664097.jpeg"
    },
    {
      name: "Spectator",
      envirement: new Set(['underground']),
      challenge_rating:"3",
      size: "medium",
      type: "abberation",
      page: "30",
      xp: 700,
      alignment:  "lawful neutral",
      armorClass: 14 ,
      hitPoints: 39 ,
      Speed: 0  ,
      STR: 8,
      STR_mod: (-1),
      DEX: 14,
      DEX_mod: (+2),
      CON: 14,
      CON_mod: (+2),
      INT: 13,
      INT_mod: (+1),
      WIS: 14,
      WIS_mod: (+2),
      CHA: 11,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/14/485/315/315/636364324602733616.png"
    },
    {
      name: "Specter",
      envirement: new Set(['urban', 'underground']),
      challenge_rating:"1",
      size: "medium",
      type: "undead",
      page: "279",
      xp: 200,
      alignment:  "chaotic evil",
      armorClass: 12 ,
      hitPoints: 22 ,
      Speed: 0,
      STR: 1,
      STR_mod: (-5),
      DEX: 14,
      DEX_mod: (+2),
      CON: 11,
      CON_mod: (+0),
      INT: 10,
      INT_mod: (+0),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 11,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/119/1000/1000/636252747399435720.jpeg"
    },
    {
      name: "Spider",
      envirement: new Set(['any']),
      challenge_rating:"0",
      size: "tiny",
      type: "beast",
      page: "337",
      xp: 10,
      alignment:"unaligned",
      armorClass: 12 ,
      hitPoints: 1 ,
      Speed: 20 ,
      STR: 2,
      STR_mod: (-4),
      DEX: 14,
      DEX_mod: (+2),
      CON: 8,
      CON_mod: (-1),
      INT: 1,
      INT_mod: (-5),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 2,
      CHA_mod: (-4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/575/315/315/636376359864842950.jpeg"
    },
    {
      name: "Spirit Naga",
      envirement: new Set(['underground']),
      challenge_rating:"8",
      size: "large",
      type: "monstrosity",
      page: "234",
      xp: 3900,
      alignment:  "chaotic evil",
      armorClass: 15,
      hitPoints: 75 ,
      Speed: 40,
      STR: 18,
      STR_mod: (+4),
      DEX: 17,
      DEX_mod: (+3),
      CON: 14,
      CON_mod: (+2),
      INT: 16,
      INT_mod: (+3),
      WIS: 15,
      WIS_mod: (+2),
      CHA: 16,
      CHA_mod: (+3),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/117/315/315/636252746851035686.jpeg"
    },
    {
      name: "Sprite",
      envirement: new Set(['forrest']),
      challenge_rating:"1/4",
      size: "tiny",
      type: "fey",
      page: "238",
      xp: 50,
      alignment:"neutral good",
      armorClass: 15,
      hitPoints: 2,
      Speed: 10,
      STR: 3,
      STR_mod: (-4),
      DEX: 18,
      DEX_mod: (+4),
      CON: 10,
      CON_mod: (+0),
      INT: 14,
      INT_mod: (+2),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 11,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/115/315/315/636252746444973630.jpeg"
    },
    {
      name: "Spy",
      envirement: new Set(['any']),
      challenge_rating:"1",
      size: "medium",
      type: "humanoid",
      page: "349",
      xp: 200,
      armorClass: 12,
      hitPoints: 27 ,
      Speed: 30,
      STR: 10,
      STR_mod: (+0),
      DEX: 15,
      DEX_mod: (+2),
      CON: 10,
      CON_mod: (+0),
      INT: 12,
      INT_mod: (+1),
      WIS: 14,
      WIS_mod: (+2),
      CHA: 16,
      CHA_mod: (+3),
      img_url:" https://media-waterdeep.cursecdn.com/attachments/2/656/humanoid.jpg"
    },
    {
      name: "Steam Mephit",
      envirement: new Set(['aquatic']),
      challenge_rating:"1/4",
      size: "small",
      type: "elemental",
      page: "217",
      xp: 50,
      alignment: "neutral evil",
      armorClass: 10 ,
      hitPoints: 21 ,
      Speed: 30,
      STR: 5,
      STR_mod: (-3),
      DEX: 11,
      DEX_mod: (+0),
      CON: 10,
      CON_mod: (+0),
      INT: 11,
      INT_mod: (+0),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 12,
      CHA_mod: (+1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/113/315/315/636252745841820724.jpeg"
    },
    {
      name: "Stirge",
      envirement: new Set(['coastal', 'desert', 'forrest', 'grass land', 'hill, mountain', 'swamp', 'underground', 'urban']),
      challenge_rating:"1/8",
      size: "tiny",
      type: "beast",
      page: "284",
      xp: 25,
      alignment:  "unaligned",
      armorClass: 14,
      hitPoints: 2 ,
      Speed: 10,
      STR: 4,
      STR_mod: (-3),
      DEX: 16,
      DEX_mod: (+3),
      CON: 11,
      CON_mod: (+0),
      INT: 2,
      INT_mod: (-4),
      WIS: 8,
      WIS_mod: (-1),
      CHA: 6,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/111/1000/1000/636252745395103202.jpeg"
    },
    {
      name: "Stone Giant",
      envirement: new Set(['hill', 'mountain', 'underground']),
      challenge_rating:"7",
      size: "huge",
      type: "giant",
      page: "156",
      xp: 2900,
      alignment: "neutral",
      armorClass: 17,
      hitPoints: 126,
      Speed: 40,
      STR: 23,
      STR_mod: (+6),
      DEX: 15,
      DEX_mod: (+2),
      CON: 20,
      CON_mod: (+5),
      INT: 10,
      INT_mod: (+0),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 9,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/109/315/315/636252744518731463.jpeg"
    },
    {
      name: "Stone Golem",
      envirement: new Set(['any']),
      challenge_rating:"10",
      size: "large ",
      type: "construct",
      page: "170",
      xp: 5900,
      alignment: "unaligned",
      armorClass: 17,
      hitPoints: 178 ,
      Speed: 30,
      STR: 22,
      STR_mod: (+6),
      DEX: 9,
      DEX_mod: (-1),
      CON: 20,
      CON_mod: (+5),
      INT: 3,
      INT_mod: (-4),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 1,
      CHA_mod: (-5),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/107/315/315/636252743780112834.jpeg"
    },
    {
      name: "Storm Giant",
      envirement: new Set(['coastal', 'aquatic ']),
      challenge_rating:"13",
      size: "huge",
      type: "giant",
      page: "156",
      xp: 10000,
      alignment:  "chaotic good",
      armorClass: 16,
      hitPoints: 230,
      Speed: 50 ,
      STR: 29,
      STR_mod: (+9),
      DEX: 14,
      DEX_mod: (+2),
      CON: 20,
      CON_mod: (+5),
      INT: 16,
      INT_mod: (+3),
      WIS: 18,
      WIS_mod: (+4),
      CHA: 18,
      CHA_mod: (+4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/105/315/315/636252743254029469.jpeg"
    },
    {
      name:"Succubus/Incubus",
      envirement: new Set(['any']),
      challenge_rating:"4",
      size: "medium",
      type: "fiend",
      page: "285",
      xp: 1100,
      alignment: "neutral evil",
      armorClass: 15,
      hitPoints: 66,
      Speed: 30,
      STR: 8,
      STR_mod: (-1),
      DEX: 17,
      DEX_mod: (+3),
      CON: 13,
      CON_mod: (+1),
      INT: 15,
      INT_mod: (+2),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 20,
      CHA_mod: (+5),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/103/315/315/636252742573312994.jpeg"
    },
    {
      name: "Swarm of Bats",
      envirement: new Set(['urban', 'mountain', 'hill', 'underground']),
      challenge_rating:"1/4",
      size: "medium",
      type: "beast",
      page: "337",
      xp: 50,
      alignment: "unaligned",
      armorClass: 12 ,
      hitPoints: 22,
      Speed: 0,
      STR: 5,
      STR_mod: (-3),
      DEX: 15,
      DEX_mod: (+2),
      CON: 10,
      CON_mod: (+0),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 4,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/9/906/315/315/636334289313689439.jpeg"
    },
    {
      name: "Swarm of Insects",
      envirement: new Set(['underground', 'desert', 'forrest', 'grass land', 'hill', 'swamp', 'urban']),
      challenge_rating:"1/2",
      size: "medium",
      type: "beast",
      page: "338",
      xp: 100,
      alignment:"unaligned",
      armorClass: 12,
      hitPoints: 22 ,
      Speed: 20,
      STR: 3,
      STR_mod: (-4),
      DEX: 13,
      DEX_mod: (+1),
      CON: 10,
      CON_mod: (+0),
      INT: 1,
      INT_mod: (-5),
      WIS: 7,
      WIS_mod: (-2),
      CHA: 1,
      CHA_mod: (-5),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Swarm of Poisonous Snakes",
      envirement: new Set(['forrest', 'swamp']),
      challenge_rating:"2",
      size: "medium",
      type: "beast",
      page: "338",
      xp: 450,
      alignment:  "unaligned",
      armorClass: 14 ,
      hitPoints: 36,
      Speed: 30,
      STR: 8,
      STR_mod: (-1),
      DEX: 18,
      DEX_mod: (+4),
      CON: 11,
      CON_mod: (+0),
      INT: 1,
      INT_mod: (-5),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 3,
      CHA_mod: (-4),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Swarm of Quippers",
      envirement: new Set(['aquatic']),
      challenge_rating:"1",
      size: "medium",
      type: "beast",
      page: "338",
      xp: 200,
      alignment:  "unaligned",
      armorClass: 13,
      hitPoints: 28,
      Speed: 0,
      STR: 13,
      STR_mod: (+1),
      DEX: 16,
      DEX_mod: (+3),
      CON: 9,
      CON_mod: (-1),
      INT: 1,
      INT_mod: (-5),
      WIS: 7,
      WIS_mod: (-2),
      CHA: 2,
      CHA_mod: (-4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/18/276/315/315/636379781035768521.jpeg"
    },
    {
      name: "Swarm of Rats",
      envirement: new Set(['urban', 'swamp']),
      challenge_rating:"1/4",
      size: "medium",
      type: "beast",
      page: "339",
      xp: 50,
      alignment:"unaligned",
      armorClass: 10,
      hitPoints: 24,
      Speed: 30,
      STR: 9,
      STR_mod: (-1),
      DEX: 11,
      DEX_mod: (+0),
      CON: 9,
      CON_mod: (-1),
      INT: 2,
      INT_mod: (-4),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 3,
      CHA_mod: (-4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/9/908/315/315/636334289541603972.jpeg"
    },
    {
      name: "Swarm of Ravens",
      envirement: new Set(['urban', 'forrest', 'hill', 'swamp']),
      challenge_rating:"1/4",
      size: "medium",
      type: "beast",
      page: "339",
      xp: 50,
      alignment:" unaligned",
      armorClass: 12 ,
      hitPoints: 24 ,
      Speed: 10,
      STR: 6,
      STR_mod: (-2),
      DEX: 14,
      DEX_mod: (+2),
      CON: 8,
      CON_mod: (-1),
      INT: 3,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 6,
      CHA_mod: (-2),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/555/315/315/636376341743427326.jpeg"
    },
    {
      name: "Tarrasque",
      envirement: new Set(['urban']),
      challenge_rating:"30",
      size: "gargantuan",
      type: "monstrosity",
      page: "286",
      xp: 155000,
      alignment: "unaligned",
      armorClass: 25,
      hitPoints: 676,
      Speed: 40,
      STR: 30,
      STR_mod: (+10),
      DEX: 11,
      DEX_mod: (+0),
      CON: 30,
      CON_mod: (+10),
      INT: 3,
      INT_mod: (-4),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 11,
      CHA_mod: (+0),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/101/1000/1000/636252741877524077.jpeg"
    },
    {
      name: "Thug",
      envirement: new Set(['urban']),
      challenge_rating:"1/2",
      size: "medium",
      type: "humanoid",
      page: "350",
      xp: 100,
      alignment: "any",
      armorClass: 11,
      hitPoints: 32,
      Speed: 30,
      STR: 15,
      STR_mod: (+2),
      DEX: 11,
      DEX_mod: (+0),
      CON: 14,
      CON_mod: (+2),
      INT: 10,
      INT_mod: (+0),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 11,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/99/1000/1000/636252741335519081.jpeg"
    },
    {
      name: "Tiger",
      envirement: new Set(['forrest', 'grass land']),
      challenge_rating:"1",
      size: "large",
      type: "beast",
      page: "339",
      xp: 200,
      alignment:  "unaligned",
      armorClass: 12 ,
      hitPoints: 37 ,
      Speed: 40,
      STR: 17,
      STR_mod: (+3),
      DEX: 15,
      DEX_mod: (+2),
      CON: 14,
      CON_mod: (+2),
      INT: 3,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Treant",
      envirement: new Set(['forrest']),
      challenge_rating:"1/8",
      size: "huge",
      type: "plant",
      page: "289",
      xp: 5000,
      alignment:"chaotic good",
      armorClass: 16,
      hitPoints: 138 ,
      Speed: 30,
      STR: 23,
      STR_mod: (+6),
      DEX: 8,
      DEX_mod: (-1),
      CON: 21,
      CON_mod: (+5),
      INT: 12,
      INT_mod: (+1),
      WIS: 16,
      WIS_mod: (+3),
      CHA: 12,
      CHA_mod: (+1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/97/315/315/636252740537990664.jpeg"
    },
    {
      name: "Tribal Warrior",
      envirement: new Set(['coastal', 'desert', 'forrest', 'grass land', 'hill', 'swamp', 'mountain', 'underground']),
      challenge_rating:"1/8",
      size: "medium",
      type: "humanoid",
      page: "350",
      xp: 25,
      alignment: "any",
      armorClass: 12,
      hitPoints: 11 ,
      Speed: 30,
      STR: 13,
      STR_mod: (+1),
      DEX: 11,
      DEX_mod: (+0),
      CON: 12,
      CON_mod: (+1),
      INT: 8,
      INT_mod: (-1),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/656/humanoid.jpg"
    },
    {
      name: "Triceratops",
      envirement: new Set(['grass land']),
      challenge_rating:"5",
      size: "huge",
      type: "beast",
      page: "80",
      xp: 1800,
      alignment:  "unaligned",
      armorClass: 13,
      hitPoints: 95,
      Speed: 50,
      STR: 22,
      STR_mod: (+6),
      DEX: 9,
      DEX_mod: (-1),
      CON: 17,
      CON_mod: (+3),
      INT: 2,
      INT_mod: (-4),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 5,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Troll",
      envirement: new Set(['artic', 'forrest', 'hill', 'swamp', 'mountain', 'underground']),
      challenge_rating:"5",
      size: "large",
      type: "giant",
      page: "291",
      xp: 1800,
      alignment: "chaotic evil",
      armorClass: 15,
      hitPoints: 84 ,
      Speed: 30,
      STR: 18,
      STR_mod: (+4),
      DEX: 13,
      DEX_mod: (+1),
      CON: 20,
      CON_mod: (+5),
      INT: 7,
      INT_mod: (-2),
      WIS: 9,
      WIS_mod: (-1),
      CHA: 7,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/95/315/315/636252739682234623.jpeg"
    },
    {
      name: "Twig Blight",
      envirement: new Set(['forrest']),
      challenge_rating:"1/8",
      size: "small",
      type: "plant",
      page: "32",
      xp: 25,
      alignment:"neutral evil",
      armorClass: 13 ,
      hitPoints: 4 ,
      Speed: 20,
      STR: 6,
      STR_mod: (-2),
      DEX: 13,
      DEX_mod: (+1),
      CON: 12,
      CON_mod: (+1),
      INT: 4,
      INT_mod: (-3),
      WIS: 8,
      WIS_mod: (-1),
      CHA: 3,
      CHA_mod: (-4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/464/1000/1000/636376286997771487.png"
    },
    {
      name: "Tyrannosaurus Rex",
      envirement: new Set(['grass land']),
      challenge_rating:"8",
      size: "huge",
      type: "beast",
      page: "80",
      xp: 3900,
      alignment:"unaligned",
      armorClass: 13,
      hitPoints: 136 ,
      Speed: 50,
      STR: 25,
      STR_mod: (+7),
      DEX: 10,
      DEX_mod: (+0),
      CON: 19,
      CON_mod: (+4),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 9,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/594/1000/1000/636376369004412963.jpeg"
    },
    {
      name: "Unicorn",
      envirement: new Set(['forrest']),
      challenge_rating:"5",
      size: "large",
      type: "celestial",
      page: "294",
      xp: 1800,
      alignment: "lawful good",
      armorClass: 12 ,
      hitPoints: 67,
      Speed: 50,
      STR: 18,
      STR_mod: (+4),
      DEX: 14,
      DEX_mod: (+2),
      CON: 15,
      CON_mod: (+2),
      INT: 11,
      INT_mod: (+0),
      WIS: 17,
      WIS_mod: (+3),
      CHA: 16,
      CHA_mod: (+3),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/93/1000/1000/636252739248798123.jpeg"
    },
    {
      name: "Vampire",
      envirement: new Set(['urban']),
      challenge_rating:"13",
      size: "medium",
      type: "undead",
      page: "297",
      xp: 10000,
      alignment: "lawful evil",
      armorClass: 16,
      hitPoints: 144 ,
      Speed: 30,
      STR: 18,
      STR_mod: (+4),
      DEX: 18,
      DEX_mod: (+4),
      CON: 18,
      CON_mod: (+4),
      INT: 17,
      INT_mod: (+3),
      WIS: 15,
      WIS_mod: (+2),
      CHA: 18,
      CHA_mod: (+4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/91/1000/1000/636252738665379794.jpeg"
    },
    {
      name: "Vampire Spawn",
      envirement: new Set(['urban']),
      challenge_rating:"5",
      size: "medium",
      type: "undead",
      page: "298",
      xp: 1800,
      alignment:  "neutral evil",
      armorClass: 15,
      hitPoints: 82,
      Speed: 30,
      STR: 16,
      STR_mod: (+3),
      DEX: 16,
      DEX_mod: (+3),
      CON: 16,
      CON_mod: (+3),
      INT: 11,
      INT_mod: (+0),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 12,
      CHA_mod: (+1),
      img_url:" https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/89/1000/1000/636252738148839638.jpeg"
    },
    {
      name: "Veteran",
      envirement: new Set(['urban']),
      challenge_rating:"3",
      size: "medium",
      type: "humanoid",
      page: "350",
      xp: 700,
      alignment: "any",
      armorClass: 17,
      hitPoints: 58,
      Speed: 30,
      STR: 16,
      STR_mod: (+3),
      DEX: 13,
      DEX_mod: (+1),
      CON: 14,
      CON_mod: (+2),
      INT: 10,
      INT_mod: (+0),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 10,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/656/humanoid.jpg"
    },
    {
      name:"Violet Fungus",
      envirement: new Set(['underground']),
      challenge_rating:"1/4",
      size: "medium",
      type: "plant",
      page: "138",
      xp: 50,
      alignment:"unaligned",
      armorClass: 5 ,
      hitPoints: 18,
      Speed: 5,
      STR: 3,
      STR_mod: (-4),
      DEX: 1,
      DEX_mod: (-5),
      CON: 10,
      CON_mod: (+0),
      INT: 1,
      INT_mod: (-5),
      WIS: 3,
      WIS_mod: (-4),
      CHA: 1,
      CHA_mod: (-5),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/573/315/315/636376357964412799.jpeg"
    },
    {
      name: "Vrock",
      envirement: new Set(['any']),
      challenge_rating:"6",
      size: "large",
      type: "fiend",
      page: "64",
      xp: 2300,
      alignment:  "chaotic evil",
      armorClass: 15,
      hitPoints: 104,
      Speed: 40,
      STR: 17,
      STR_mod: (+3),
      DEX: 15,
      DEX_mod: (+2),
      CON: 18,
      CON_mod: (+4),
      INT: 8,
      INT_mod: (-1),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/87/315/315/636252737538172594.jpeg"
    },
    {
      name: "Vulture",
      envirement: new Set(['desert', 'grass land', 'hill']),
      challenge_rating:"0",
      size: "medium",
      type: "beast",
      page: "339",
      xp: 10,
      alignment: "unaligned",
      armorClass: 10 ,
      hitPoints: 5,
      Speed: 10,
      STR: 7,
      STR_mod: (-2),
      DEX: 10,
      DEX_mod: (+0),
      CON: 13,
      CON_mod: (+1),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 4,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Warhorse",
      envirement: new Set(['urban']),
      challenge_rating:"1/2",
      size: "large",
      type: "beast",
      page: "340",
      xp: 100,
      alignment: "unaligned",
      armorClass: 11 ,
      hitPoints: 19,
      Speed: 60,
      STR: 18,
      STR_mod: (+4),
      DEX: 12,
      DEX_mod: (+1),
      CON: 13,
      CON_mod: (+1),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 7,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Warhorse Skeleton",
      envirement: new Set(['urban']),
      challenge_rating:"1/2",
      size: "large",
      type: "beast",
      page: "273",
      xp: 100,
      alignment: "lawful evil",
      armorClass: 13,
      hitPoints: 22,
      Speed: 60,
      STR: 18,
      STR_mod: (+4),
      DEX: 12,
      DEX_mod: (+1),
      CON: 15,
      CON_mod: (+2),
      INT: 2,
      INT_mod: (-4),
      WIS: 8,
      WIS_mod: (-1),
      CHA: 5,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/660/undead.jpg"
    },
    {
      name: "Water Elemental",
      envirement: new Set(['any']),
      challenge_rating:"5",
      size: "large",
      type: "elemental",
      page: "125",
      xp: 1800,
      alignment:  "neutral",
      armorClass: 14,
      hitPoints: 114,
      Speed: 30,
      STR: 18,
      STR_mod: (+4),
      DEX: 14,
      DEX_mod: (+2),
      CON: 18,
      CON_mod: (+4),
      INT: 5,
      INT_mod: (-3),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/84/315/315/636252736680781387.jpeg"
    },
    {
      name: "Weasel",
      envirement: new Set(['any']),
      challenge_rating:"0",
      size: "tiny",
      type: "beast",
      page: "340",
      xp: 10,
      alignment: "unaligned",
      armorClass: 13 ,
      hitPoints: 1 ,
      Speed: 30,
      STR: 3,
      STR_mod: (-4),
      DEX: 16,
      DEX_mod: (+3),
      CON: 8,
      CON_mod: (-1),
      INT: 2,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 3,
      CHA_mod: (-4),
      img_url: "https://media-waterdeep.cursecdn.com/attachments/2/648/beast.jpg"
    },
    {
      name: "Werebear",
      envirement: new Set(['urban', 'forest', 'hill']),
      challenge_rating:"5",
      size: "medium",
      type: "humanoid",
      page: "208",
      xp: 1800,
      alignment: "neutral good",
      armorClass: 10,
      hitPoints: 135,
      Speed: 30,
      STR: 19,
      STR_mod: (+4),
      DEX: 10,
      DEX_mod: (+0),
      CON: 17,
      CON_mod: (+3),
      INT: 11,
      INT_mod: (+0),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 12,
      CHA_mod: (+1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/82/1000/1000/636252736005297867.jpeg"
    },
    {
      name: "Wereboar",
      envirement: new Set(['urban', 'forest', 'hill']),
      challenge_rating:"4",
      size: "medium",
      type: "humanoid",
      page: "209",
      xp: 1100,
      alignment: "neutral evil",
      armorClass: 10,
      hitPoints: 78,
      Speed: 30,
      STR: 17,
      STR_mod: (+3),
      DEX: 10,
      DEX_mod: (+0),
      CON: 15,
      CON_mod: (+2),
      INT: 10,
      INT_mod: (+0),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/80/315/315/636252735506840152.jpeg"
    },
    {
      name: "Wererat",
      envirement: new Set(['urban', 'forest', 'hill']),
      challenge_rating:"2",
      size: "medium",
      type: "humanoid",
      page: "209",
      xp: 450,
      alignment:  "lawful evil",
      armorClass: 12 ,
      hitPoints: 33,
      Speed: 30,
      STR: 10,
      STR_mod: (+0),
      DEX: 15,
      DEX_mod: (+2),
      CON: 12,
      CON_mod: (+1),
      INT: 11,
      INT_mod: (+0),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/78/1000/1000/636252735121410517.jpeg"
    },
    {
      name: "Weretiger",
      envirement: new Set(['urban', 'forest', 'hill']),
      challenge_rating:"4",
      size: "medium",
      type: "humanoid",
      page: "210",
      xp: 1100,
      alignment:  "neutral",
      armorClass: 12 ,
      hitPoints: 120 ,
      Speed: 30,
      STR: 17,
      STR_mod: (+3),
      DEX: 15,
      DEX_mod: (+2),
      CON: 16,
      CON_mod: (+3),
      INT: 10,
      INT_mod: (+0),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 11,
      CHA_mod: (+0),
      img_url:"https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/76/1000/1000/636252734783831163.jpeg"
    },
    {
      name: "Werewolf",
      envirement: new Set(['urban', 'forest', 'hill']),
      challenge_rating:"3",
      size: "medium",
      type: "humanoid",
      page: "211",
      xp: 700,
      alignment: "chaotic evil",
      armorClass: 11,
      hitPoints: 58 ,
      Speed: 30 ,
      STR: 15,
      STR_mod: (+2),
      DEX: 13,
      DEX_mod: (+1),
      CON: 14,
      CON_mod: (+2),
      INT: 10,
      INT_mod: (+0),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 10,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/74/1000/1000/636252734224239957.jpeg"
    },
    {
      name:"White Dragon Wyrmling",
      envirement: new Set(['any']),
      challenge_rating:"2",
      size: "medium",
      type: "dragon",
      page: "102",
      xp: 450,
      alignment:  "chaotic evil",
      armorClass: 16,
      hitPoints: 32,
      Speed: 30,
      STR: 14,
      STR_mod: (+2),
      DEX: 10,
      DEX_mod: (+0),
      CON: 14,
      CON_mod: (+2),
      INT: 5,
      INT_mod: (-3),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 11,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/415/1000/1000/636252789083357808.jpeg"
    },
    {
      name: "Wight",
      envirement: new Set(['desert', 'swamp', 'underground', 'urban']),
      challenge_rating:"3",
      size: "medium",
      type: "undead",
      page: "300",
      xp: 700,
      alignment: "neutral evil",
      armorClass: 14,
      hitPoints: 45,
      Speed: 30,
      STR: 15,
      STR_mod: (+2),
      DEX: 14,
      DEX_mod: (+2),
      CON: 16,
      CON_mod: (+3),
      INT: 10,
      INT_mod: (+0),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 15,
      CHA_mod: (+2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/56/315/315/636252726349692861.jpeg"
    },
    {
      name: "Will-o'-Wisp",
      envirement: new Set(['urban', 'forest', 'swamp']),
      challenge_rating:"2",
      size: "tiny",
      type: "undead",
      page: "301",
      xp: 450,
      alignment: "chaotic evil",
      armorClass: 19 ,
      hitPoints: 22,
      Speed: 0 ,
      STR: 1,
      STR_mod: (-5),
      DEX: 28,
      DEX_mod: (+9),
      CON: 10,
      CON_mod: (+0),
      INT: 13,
      INT_mod: (+1),
      WIS: 14,
      WIS_mod: (+2),
      CHA: 11,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/585/315/315/636376363763232290.jpeg"
    },
    {
      name: "Winter Wolf",
      envirement: new Set(['arctic']),
      challenge_rating:"3",
      size: "large",
      type: "monstrosity",
      page: "340",
      xp: 700,
      alignment: "neutral evil",
      armorClass: 13,
      hitPoints: 75,
      Speed: 50,
      STR: 18,
      STR_mod: (+4),
      DEX: 13,
      DEX_mod: (+1),
      CON: 14,
      CON_mod: (+2),
      INT: 7,
      INT_mod: (-2),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/54/315/315/636252725270715296.jpeg"
    },
    {
      name: "Wolf",
      envirement: new Set(['urban', 'forest', 'hill']),
      challenge_rating:"1/4",
      size: "medium",
      type: "beast",
      page: "341",
      xp: 50,
      alignment: "unaligned",
      armorClass: 13,
      hitPoints: 11,
      Speed: 40,
      STR: 12,
      STR_mod: (+1),
      DEX: 15,
      DEX_mod: (+2),
      CON: 12,
      CON_mod: (+1),
      INT: 3,
      INT_mod: (-4),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 6,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/16/482/1000/1000/636376300223855327.jpeg"
    },
    {
      name: "Worg",
      envirement: new Set(['grass land', 'forest', 'hill']),
      challenge_rating:"1/2",
      size: "large",
      type: "monstrosity",
      page: "341",
      xp: 100,
      alignment:  "neutral evil",
      armorClass: 13,
      hitPoints: 26 ,
      Speed: 50,
      STR: 16,
      STR_mod: (+3),
      DEX: 13,
      DEX_mod: (+1),
      CON: 13,
      CON_mod: (+1),
      INT: 7,
      INT_mod: (-2),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 8,
      CHA_mod: (-1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/52/1000/1000/636252724662073178.jpeg"
    },
    {
      name: "Wraith",
      envirement: new Set(['underground']),
      challenge_rating:"5",
      size: "medium",
      type: "undead",
      page: "302",
      xp: 1800,
      alignment: "neutral evil",
      armorClass: 13 ,
      hitPoints: 67,
      Speed: 0,
      STR: 6,
      STR_mod: (-2),
      DEX: 16,
      DEX_mod: (+3),
      CON: 16,
      CON_mod: (+3),
      INT: 12,
      INT_mod: (+1),
      WIS: 14,
      WIS_mod: (+2),
      CHA: 15,
      CHA_mod: (+2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/50/1000/1000/636252724191790008.jpeg"
    },
    {
      name: "Wyvern",
      envirement: new Set([ 'mountain', 'hill']),
      challenge_rating:"6",
      size: "large",
      type: "dragon",
      page: "303",
      xp: 2300,
      alignment: "unaligned",
      armorClass: 13,
      hitPoints: 110, 
      Speed: 20,
      STR: 19,
      STR_mod: (+4),
      DEX: 10,
      DEX_mod: (+0),
      CON: 16,
      CON_mod: (+3),
      INT: 5,
      INT_mod: (-3),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 6,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/48/315/315/636252723695596000.jpeg"
    },
    {
      name: "Xorn",
      envirement: new Set(['underground']),
      challenge_rating:"5",
      size: "medium",
      type: "elemental",
      page: "304",
      xp: 1800,
      alignment: "neutral",
      armorClass: 19,
      hitPoints: 73,
      Speed: 20,
      STR: 17,
      STR_mod: (+3),
      DEX: 10,
      DEX_mod: (+0),
      CON: 22,
      CON_mod: (+6),
      INT: 11,
      INT_mod: (+0),
      WIS: 10,
      WIS_mod: (+0),
      CHA: 11,
      CHA_mod: (+0),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/46/1000/1000/636252723241554579.jpeg"
    },
    {
      name: "Yeti",
      envirement: new Set(['arctic']),
      challenge_rating:"9",
      size: "large",
      type: "monstrosity",
      page: "306",
      xp: 5000,
      alignment: " chaotic evil",
      armorClass: 12,
      hitPoints: 51,
      Speed: 40,
      STR: 18,
      STR_mod: (+4),
      DEX: 13,
      DEX_mod: (+1),
      CON: 16,
      CON_mod: (+3),
      INT: 8,
      INT_mod: (-1),
      WIS: 12,
      WIS_mod: (+1),
      CHA: 7,
      CHA_mod: (-2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/8/662/1000/1000/636313413410825930.jpeg"
    },
    {
      name: "Young Black Dragon",
      envirement: new Set(['any']),
      challenge_rating:"7",
      size: "large",
      type: "dragon",
      page: "88",
      xp: 2900,
      alignment:"chaotic evil",
      armorClass: 18,
      hitPoints: 127 ,
      Speed: 40,
      STR: 19,
      STR_mod: (+4),
      DEX: 14,
      DEX_mod: (+2),
      CON: 17,
      CON_mod: (+3),
      INT: 12,
      INT_mod: (+1),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 15,
      CHA_mod: (+2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/70/1000/1000/636252732861675698.jpeg"
    },
    {
      name: "Young Blue Dragon",
      envirement: new Set(['any']),
      challenge_rating:"9",
      size: "large",
      type: "dragon",
      page: "91",
      xp: 5000,
      alignment: "lawful evil",
      armorClass: 18,
      hitPoints: 152 ,
      Speed: 40,
      STR: 21,
      STR_mod: (+5),
      DEX: 10,
      DEX_mod: (+0),
      CON: 19,
      CON_mod: (+4),
      INT: 14,
      INT_mod: (+2),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 17,
      CHA_mod: (+3),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/68/1000/1000/636252732434296782.jpeg"
    },
    {
      name:"Young Brass Dragon",
      envirement: new Set(['any']),
      challenge_rating:"6",
      size: "large",
      type: "dragon",
      page: "105",
      xp: 2300,
      alignment: "chaotic good",
      armorClass: 17,
      hitPoints: 110,
      Speed: 40,
      STR: 19,
      STR_mod: (+4),
      DEX: 10,
      DEX_mod: (+0),
      CON: 17,
      CON_mod: (+3),
      INT: 12,
      INT_mod: (+1),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 15,
      CHA_mod: (+2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/66/1000/1000/636252731911060874.jpeg"
    },
    {
      name: "Young Bronze Dragon",
      envirement: new Set(['any']),
      challenge_rating:"8",
      size: "large",
      type: "dragon",
      page: "108",
      xp: 3900,
      alignment: "lawful good",
      armorClass: 18,
      hitPoints: 142,
      Speed: 40,
      STR: 21,
      STR_mod: (+5),
      DEX: 10,
      DEX_mod: (+0),
      CON: 19,
      CON_mod: (+4),
      INT: 14,
      INT_mod: (+2),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 17,
      CHA_mod: (+3),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/64/315/315/636252731269768088.jpeg"
    },
    {
      name: "Young Copper Dragon",
      envirement: new Set(['any']),
      challenge_rating:"8",
      size: "large",
      type: "dragon",
      page: "108",
      xp: 3900,
      alignment: "chaotic good",
      armorClass: 17,
      hitPoints: 119 ,
      Speed: 40,
      STR: 19,
      STR_mod: (+4),
      DEX: 12,
      DEX_mod: (+1),
      CON: 17,
      CON_mod: (+3),
      INT: 16,
      INT_mod: (+3),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 15,
      CHA_mod: (+2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/62/1000/1000/636252729761648292.jpeg"
    },
    {
      name:"Young Gold Dragon",
      envirement: new Set(['any']),
      challenge_rating:"10",
      size: "large",
      type: "dragon",
      page: "115",
      xp: 5900,
      alignment: "lawful good",
      armorClass: 18,
      hitPoints: 178 ,
      Speed: 40 ,
      STR: 23,
      STR_mod: (+6),
      DEX: 14,
      DEX_mod: (+2),
      CON: 21,
      CON_mod: (+5),
      INT: 16,
      INT_mod: (+3),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 20,
      CHA_mod: (+5),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/60/1000/1000/636252729283446963.jpeg"
    },
    {
      name: "Young Green Dragon",
      envirement: new Set(['any']),
      challenge_rating:"8",
      size: "large",
      type: "drgaon",
      page: "94",
      xp: 3900,
      alignment: "lawful evil",
      armorClass: 18,
      hitPoints: 136,
      Speed: 40,
      STR: 19,
      STR_mod: (+4),
      DEX: 12,
      DEX_mod: (+1),
      CON: 17,
      CON_mod: (+3),
      INT: 16,
      INT_mod: (+3),
      WIS: 13,
      WIS_mod: (+1),
      CHA: 15,
      CHA_mod: (+2),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/58/315/315/636252728834677623.jpeg"
    },
    {
      name: "Young Red Dragon",
      envirement: new Set(['any']),
      challenge_rating:"10",
      size: "large",
      type: "dragon",
      page: "98",
      xp: 5900,
      alignment: " chaotic evil",
      armorClass: 18,
      hitPoints: 178,
      Speed: 40,
      STR: 23,
      STR_mod: (+6),
      DEX: 10,
      DEX_mod: (+0),
      CON: 21,
      CON_mod: (+5),
      INT: 14,
      INT_mod: (+2),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 19,
      CHA_mod: (+4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/399/315/315/636252784386259001.jpeg"
    },
    {
      name: "Young Silver Dragon",
      envirement: new Set(['any']),
      challenge_rating:"9",
      size: "large",
      type: "dragon",
      page: "118",
      xp: 5000,
      alignment: "lawful good",
      armorClass: 18,
      hitPoints: 168,
      Speed: 40,
      STR: 23,
      STR_mod: (+6),
      DEX: 10,
      DEX_mod: (+0),
      CON: 21,
      CON_mod: (+5),
      INT: 14,
      INT_mod: (+2),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 19,
      CHA_mod: (+4),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/401/315/315/636252784740667730.jpeg"
    },
    {
      name: "Young White Dragon",
      envirement: new Set(['any']),
      challenge_rating:"6",
      size: "large",
      type: "dragon",
      page: "101",
      xp: 2300,
      alignment: "chaotic evil",
      armorClass: 17,
      hitPoints: 133,
      Speed: 40,
      STR: 18,
      STR_mod: (+4),
      DEX: 10,
      DEX_mod: (+0),
      CON: 18,
      CON_mod: (+4),
      INT: 6,
      INT_mod: (-2),
      WIS: 11,
      WIS_mod: (+0),
      CHA: 12,
      CHA_mod: (+1),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/403/1000/1000/636252785358767533.jpeg"
    },
    {
      name: "Zombie",
      envirement: new Set(['urban']),
      challenge_rating:"1/4",
      size: "medium",
      type: "undead",
      page: "316",
      xp: 50,
      alignment: "neutral evil",
      armorClass: 8 ,
      hitPoints: 22,
      Speed: 20,
      STR: 13,
      STR_mod: (+1),
      DEX: 6,
      DEX_mod: (-2),
      CON: 16,
      CON_mod: (+3),
      INT: 3,
      INT_mod: (-4),
      WIS: 6,
      WIS_mod: (-2),
      CHA: 5,
      CHA_mod: (-3),
      img_url: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/71/1000/1000/636252733510786769.jpeg"
    }
  ]

export default monsters;